server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:accountdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
