# @author "Venkata Praveen Kumar Sadu"
spring.application.name=gateway-service
spring.logging.structured.format=json

# Map Actuator /actuator/health to /health as per requirements
management.endpoints.web.base-path=/